apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipe-operator
rules:
  - apiGroups: [apps]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [patch, update]
  - apiGroups: [apps]
    resources: [deployments/scale, statefulsets/scale]
    verbs: [get, patch, update]
  - apiGroups: [""]
    resources: [pods]
    verbs: [delete]
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [create, get]
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [create, patch, delete]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [patch]           # cordon / uncordon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipe-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipe-operator
subjects:
  - kind: ServiceAccount
    name: pipe
    namespace: pipe
